[package]
name = "vhapi-cli"
version = "0.1.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
yaml-rust = "0.4"

[dependencies.vhapi]
path = "../"