[package]
name = "vhapi"
version = "0.1.0"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
nom = "5"
nom_locate = "2"
nom-greedyerror = "0.2"
nom-tracable = "0.5"

yaml-rust = "0.4"
linked-hash-map = ">=0.0.9, <0.6"

[features]
default = []
trace = ["nom-tracable/trace"]

[workspace]
members = ["vhapi-cli"]